export type Course = {
  id?: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  description?: string | null;
  thumbnail_url?: string | null;
  video_preview_url?: string | null;
  price?: number | null;
  original_price?: number | null;
  currency?: string | null;
  level?: string | null;
  language?: string | null;
  duration_hours?: number | null;
  total_lectures?: number | null;
  requirements?: any;
  what_will_learn?: any;
  target_audience?: any;
  status?: string | null;
  is_free?: boolean | null;
  has_certificate?: boolean | null;
  has_lifetime_access?: boolean | null;
  has_mobile_access?: boolean | null;
  total_students?: number | null;
  avg_rating?: number | null;
  total_ratings?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
};
